### ISSUE TITLE
"checkpoint" element not hidden when map first loaded

### ISSUE THREAD

**Issue by Protoster** [chipsTM/tm-hud-picker#1]
When the "race > checkpoint" HUD element is hidden, it still appears when you first load into a map.
It should remain hidden once I've set it to be hidden.
It is possible to hide it again by either toggling the setting on and off, or reloading the addon.
Here's a screenshot showing the settings menu where "checkpoint" is hidden, along with the HUD element that should be hidden (circled). The second checkpoint readout at the bottom is from another addon.
![Screenshot 2023-09-19 013610](https://github.com/chipsTM/tm-hud-picker/assets/5383872/fc0c5d02-8037-43fb-a09c-f85a8ffec3dc)

**Comment by chipsTM** [comment]
Hey thanks for reporting the issue. Can you confirm it's been fixed in the newest update?

**Comment by Protoster** [comment]
Confirmed, issue fixed. Thanks 👍
