### ISSUE TITLE
add support for current medal display

### ISSUE THREAD

**Issue by ezio416** [chipsTM/tm-hud-picker#4]
Using MLHook's UI layers browser, it seems this is part of `UIModule_Race_Record`. Currently I can hide the records table but not this display above it that shows at the beginning of a time attack race

<img width="197" alt="Screenshot 2024-01-19 153859" src="https://github.com/chipsTM/tm-hud-picker/assets/37951898/23f5d184-1561-4e42-9d9a-d49e897c7fe8">

**Comment by chipsTM** [comment]
Fixed with https://github.com/chipsTM/tm-hud-picker/commit/cf13e82e498b361b664c4facd28672f07f93928f
