### ISSUE TITLE
Broken since Update

### ISSUE THREAD

**Issue by tobiasarndt** [chipsTM/tm-hud-picker#5]
HUDPicker is currently not working for me. When I open it's settings, it keeps throwing the following exception:
```
Script exception: Jason value is not a number!
HUDPicker.op/:/src/GameInfo.as (line 47, column 13)
  #0 bool GameInfo::IsPlaying() (HUDPicker.op/:/src/GameInfo.as line 47)
  #1 void RenderHUDTreeSettings() (HUDPicker.op/:/src/Settings.as line 6)
```

**Comment by chipsTM** [comment]
Can you check the `OpenplanetNext\PluginStorage\HUDPicker\settings.json` file? Its possible it is corrupt (i.e. it shows null values)

**Comment by tobiasarndt** [comment]
Yeah, my file reads:
```{"Race":null,"layercount":27}```
I tried uninstalling and reinstalling it, but it's still the same.

**Comment by chipsTM** [comment]
Can you uninstall the plugin, delete the settings file, restart game, then re-install the plugin when you're playing a map?

**Comment by tobiasarndt** [comment]
That worked. Thanks for the help! Are the files in the plugin storage not deleted on uninstall?

**Comment by chipsTM** [comment]
They are not, each plugin handles this manually (if cleanup is needed)

**Comment by tobiasarndt** [comment]
Good to know. Thanks again for you quick help!
