### ISSUE TITLE
exceptions with `uiDic`

### ISSUE THREAD

**Issue by ezio416** [chipsTM/tm-hud-picker#6]
Just started happening today, and restarting the game doesn't help. My settings have been reset (not a huge deal but probably notable) and the plugin isn't working at all. The first exception below happens on game/script engine boot, and the second is thrown twice on every reload and every frame when the settings tab is open:
![Screenshot 2024-04-20 114459](https://github.com/chipsTM/tm-hud-picker/assets/37951898/6f42bcd5-a4fc-4dc4-b1f5-fc7df7877720)
![Screenshot 2024-04-20 114512](https://github.com/chipsTM/tm-hud-picker/assets/37951898/938457b1-e329-4275-90ac-6c740b8ba3b7)

**Comment by chipsTM** [comment]
I don't know why the file gets in a bad state, but maybe following the thread here might help: https://github.com/chipsTM/tm-hud-picker/issues/5

**Comment by ezio416** [comment]
that worked, thank you
